sudo: false
language: node_js
node_js:
- 6

env:
  matrix:
    - BROWSER=chrome  BVER=stable
    - BROWSER=chrome  BVER=beta
    - BROWSER=chrome  BVER=unstable
    - BROWSER=firefox BVER=stable
    - BROWSER=firefox BVER=beta
    - BROWSER=firefox BVER=nightly
    - BROWSER=firefox BVER=esr

matrix:
  fast_finish: true

  allow_failures:
    - env: BROWSER=chrome  BVER=unstable
    - env: BROWSER=firefox BVER=nightly
    - env: BROWSER=firefox BVER=esr

before_script:
  - ./node_modules/travis-multirunner/setup.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - node_modules/.bin/grunt
  - npm test

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true

