dist: trusty
language: node_js
node_js:
- 6

addons:
  apt:
    packages:
      - pulseaudio

env:
  global:
    - DISPLAY=:99.0

  matrix:
    - BROWSER=chrome  BVER=stable
    - BROWSER=chrome  BVER=stable CHROMEEXPERIMENT=false
    - BROWSER=chrome  BVER=beta
    - BROWSER=chrome  BVER=beta CHROMEEXPERIMENT=false
    - BROWSER=chrome  BVER=unstable
    - BROWSER=firefox BVER=stable
    - BROWSER=firefox BVER=beta
    - BROWSER=firefox BVER=nightly
    - BROWSER=firefox BVER=esr

matrix:
  fast_finish: true

  allow_failures:
    - env: BROWSER=chrome  BVER=unstable
    - env: BROWSER=firefox BVER=nightly

before_script:
  - export CHROME_BIN=browsers/bin/chrome-${BVER}
  - export FIREFOX_BIN=browsers/bin/firefox-${BVER}
  - sh -e /etc/init.d/xvfb start
  - pulseaudio --start

script:
  - node_modules/.bin/grunt
  - npm test

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true

notifications:
  email:
    recipients:
      forward-webrtc-github@webrtc.org
    on_success: change
    on_failure: always
